# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  myBranch: $(Build.SourceBranch)

stages:
- stage: General
  jobs:
  - job: GeneralJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo $(myBranch)
    condition: eq(variables['myBranch'], 'refs/heads/featureX')

#- stage: PipelineScan
#  jobs:
#  - job: featureX_Branch_Job
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - bash: echo 'Entro a Pipeline Scan'
#    condition: eq(variables['myBranch'], 'refs/heads/featureX')

#- stage: PolicyScan
#  jobs:
#  - job: master_Branch_Job
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - bash: echo 'Entro a Policy Scan'
#    condition: eq(variables['myBranch'], 'refs/heads/master')
