# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
   - refs/heads/master
   - refs/heads/dev
   - refs/heads/featureX

pool:
  vmImage: 'ubuntu-latest'

stages:
# In Veracode Stage it will execute Pipeline Scan or Sandbox Scan or Policy Scan depending on the branch under execution, which could be
# 'featureX' or 'dev' or 'master' respectively.
- stage: Veracode
  jobs:
#  - job: GeneralJob
#    steps:
#    - bash: echo $(Build.SourceBranch)
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - script: ls


  - job: PipelineScan
    steps:
    - script: echo 'Veracode SAST - Pipeline Scan'
    condition: eq(variables['build.sourceBranch'], 'refs/heads/featureX')
  - job: SandboxScan
    steps:
    - script: echo 'Veracode SAST - Sandbox Scan'
    condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
  - job: PolicyScan
    steps:
    - script: echo 'Veracode SAST - Policy Scan'
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')

