# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  myBranch: $(Build.SourceBranch)

stages:
- stage: General
  jobs:
  - job: GeneralJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo $(myBranch)

- stage: PipelineScan
  condition: eq(variables['myBranch'], 'refs/heads/featureX')
  jobs:
  - job: featureX_Branch_Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo $(myBranch)

- stage: PolicyScan
  condition: eq(variables['myBranch'], 'refs/heads/master')
  jobs:
  - job: master_Branch_Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo $(myBranch)
