# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Veracode
  jobs:
#  - job: GeneralJob
#    steps:
#    - bash: echo $(Build.SourceBranch)
  - job: PipelineScan
    steps:
    - script: echo 'Pipeline Scan'
    condition: eq(variables['build.sourceBranch'], 'refs/heads/featureX')
  - job: PolicyScan
    steps:
    - script: echo 'Policy Scan'
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')

#- stage: PipelineScan
#  jobs:
#  - job: featureX_Branch_Job
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - bash: echo 'Entro a Pipeline Scan'
#    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')

#- stage: PolicyScan
#  jobs:
#  - job: master_Branch_Job
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - bash: echo 'Entro a Policy Scan'
#    condition: eq(variables['myBranch'], 'refs/heads/master')
