# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  myBranch: variables['Build.SourceBranch']

stages:
- stage: PipelineScan
  jobs:
  - job: featureX_Branch_Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo $(myBranch)

