name: featureX Branch - Base Pipeline

on:
    push:
        branches:
        - 'featureX'

jobs:
    call-workflow-1-in-local-repo:
        uses: ./.github/workflows/VeracodeContainerSecurity.yml
        secrets: inherit