name: master Branch - Base Pipeline

on:
    pull_request:
        types:
            [opened, reopened]
        branches:
            - 'master'

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checking Out Code Repo
              uses: actions/checkout@v2

            # Clean output directory
            - name: Clean Output Directory
              working-directory: ./app
              run: mvn -B clean

            #Setting Java
            - name: Set up JDK 8
              uses: actions/setup-java@v2
              with:
                java-version: '8'
                distribution: 'temurin'

            # Build the project by using Maven
            - name: Build with Maven
              working-directory: ./app
              run: mvn -B package --file pom.xml

            # Publishing artifacts
            - name: Step 3 - Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@v3
              with: 
                name: MyBuiltArtifact
                path: ./app/target/verademo.war

    VeracodePolicyScan:
        needs: Build
        uses: ./.github/workflows/VeracodePolicyScan.yml
        secrets: inherit
          
    VeracodeContainerSecurity:
        needs: Build
        uses: ./.github/workflows/VeracodeContainerSecurity.yml
        secrets: inherit

    CheckingResults:
        needs: [VeracodePolicyScan, VeracodeContainerSecurity]
        runs-on: ubuntu-latest
        steps:

            # Getting Artifacts
            - name: Getting Container Security Scan Results
              uses: actions/download-artifact@v3
              with:
                name: VeracodeContainerSecurityResults

            - name: Validating Container Security Scan Results
              if: ${{ success() }}
              run: |
                echo 'VALIDATING VERACODE CONTAINER SECURITY RESULTS...'
                PASS=$(jq -r '."Policy Passed"' results.json)
                echo "Passed policy: $PASS"
                if $PASS; then
                  exit 0
                else
                  exit 1
                fi

          