# This is a basic workflow to help you understan how to integrate some Veracode analysis with Actions

name: Veracode_GitHub_Actions

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ featureX ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Clean output directory
      - name: Clean Output Directory
        run: mvn -B clean

      #Setting Java
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      # Build the project by using Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls ./target

