name: VeracodeContainerSecurity

on:
  workflow_call:

jobs:
    CS:
        runs-on: ubuntu-latest
        steps:

            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: ls
                        