name: VeracodeContainerSecurity

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

        - name: Branch name
          run: |
            
# Veracode container scanning, failing on failed policy

trigger:
  - none
  
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: Bash@3
    displayName: 'Container image scan'
    inputs:
      targetType: 'inline'
      script: |
        echo ${{ github.github_server_url }}'/'${{ github.GITHUB_REPOSITORY }}