name: VeracodeContainerSecurity

on:
  workflow_call:
    inputs:
        project-folder:
            description: Root folder with app and artifacts to be uploaded
            type: string
            default: .

jobs:
    CS:
        runs-on: ubuntu-latest
        steps:

            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: |
                echo 'Project Folder: '${{ inputs.project-folder }}

            - name: Branch name
              run: |
                echo 'Branch Name: '${{ github.ref_name }}          