name: VeracodeContainerSecurity

on:
  workflow_call:

jobs:
  ContainerScan:
    runs-on: ubuntu-latest
    steps:

        # Runs Veracode Container Security - Failing on failed Bult-In Policy
        - name: VERACODE CONTAINER SECURITY
          if: ${{ success() }}
          env:
            VID: ${{ SECRETS.VID }}
            VKEY: ${{ SECRETS.VKEY }}
            REPO_URL: ${{ GITHUB.server_url }}/${{ GITHUB.REPOSITORY }}
          run: |
            echo '================================'
            echo '== SCANNING REPO '$REPO_URL
            echo '================================'
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            export VERACODE_API_KEY_ID=$VID
            export VERACODE_API_KEY_SECRET=$VKEY
            ./veracode scan --type repo --source $REPO_URL --output cs_results.json

        # Publishing artifacts
#        - name: Step 3 - Use the Upload Artifact GitHub Action
#          uses: actions/upload-artifact@v3
#          with: 
#            name: VeracodeContainerSecurityResults
#            path: ./cs_results.json

                  # Getting Container Security Scan Results
#                  - name: Getting Container Security Scan Results
#                    uses: actions/download-artifact@v3
#                    with:
#                      name: VeracodeContainerSecurityResults
      
        - name: Validating Container Security Scan Results
          if: ${{ success() }}
          run: |
            echo 'VALIDATING VERACODE CONTAINER SECURITY RESULTS...'
            PASS=$(jq -r '."policy-passed"' cs_results.json)
            echo "Passed policy: $PASS"
            if $PASS; then
              exit 0
            else
              exit 1
            fi
