name: Veracode Policy Scan

on:
  workflow_call:

jobs:
  PolicyScan:
    runs-on: ubuntu-latest
    steps:

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checking Out Code Repo
          uses: actions/checkout@v2

        #Gets the artifact
        - name: Downloading artifact
          uses: actions/download-artifact@v3
          with:
            name: MyBuiltArtifact

        # Runs Veracode SAST Scan
        - name: VERACODE SAST - POLICY SCAN
          if: ${{ success() }}
          uses: veracode/veracode-uploadandscan-action@0.2.6 
          with:
            appname: 'verademo'
            createprofile: false
            filepath: 'verademo.war'
            vid: '${{ SECRETS.VID }}'
            vkey: '${{ SECRETS.VKEY }}'
            version: '${{ github.run_id }}'
            deleteincompletescan: 2

        # Verify SAST results to control workflow 
        - name: Validating SAST Scan Results
          if: ${{ success() }}
          run: |
            chmod 777 -R shell_scripts
            echo '======================================================='
            echo 'VALIDATING VERACODE SAST RESULTS...'
            echo '======================================================='
            ./shell_scripts/veracode-scan-results.sh ${{ SECRETS.VID }} ${{ SECRETS.VKEY }} verademo

