# This is a basic workflow to help you understan how to integrate some Veracode analysis with Actions

name: VeracodePolicyScan

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Clean output directory
      - name: Clean Output Directory
        run: mvn -B clean

      #Setting Java
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      # Build the project by using Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls ./target

      - name: Branch name
        run: |
          echo 'Branch Name: '${{ github.ref_name }}

      # Runs Veracode Policy Scan
      - name: VERACODE POLICY SCAN - UPLOAD AND SCAN
        if: ${{ success() }}
        uses: veracode/veracode-uploadandscan-action@0.2.4
        env:
          VID: ${{ SECRETS.VID }}
          VKEY: ${{ SECRETS.VKEY }}
        with:
          appname: 'VERADEMO_GITHUB_ACTIONS'
          createprofile: false
          filepath: './target/verademo.war'
          version: '${{ github.run_id }}'
          vid: '$VID'
          vkey: '$VKEY'
          scanallnonfataltoplevelmodules: true
          deleteincompletescan: 1   

      #Gets Veracode Policy Scan Results
      - name: VERACODE POLICY SCAN - RESULTS
        if: ${{ success() }}
        env:
          VID: ${{ SECRETS.VID }}
          VKEY: ${{ SECRETS.VKEY }}
        run: |
            echo '[INFO] Getting Policy Scan Results...'
            chmod 755 veracode-scan-results.sh
            ./veracode-scan-results.sh $VID $VKEY VERADEMO_GITHUB_ACTIONS
