name: Veracode Pipeline Scan

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

        #Gets the artifact
        - name: Downloading artifact
          uses: actions/download-artifact@v3
          with:
            name: MyBuiltArtifact

        - name: Display structure of downloaded files
          run: ls -R