name: VeracodeContainerSecurity

on:
  workflow_call:

jobs:
  ContainerScan:
    runs-on: ubuntu-latest
    steps:

        # Runs Veracode Container Security - Failing on failed Bult-In Policy
        - name: VERACODE CONTAINER SECURITY
          if: ${{ success() }}
          env:
            VID: ${{ SECRETS.VID }}
            VKEY: ${{ SECRETS.VKEY }}
            REPO_URL: ${{ GITHUB.server_url }}/${{ GITHUB.REPOSITORY }}
          run: |
            echo '================================'
            echo '== SCANNING REPO '$REPO_URL
            echo '================================'
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            export VERACODE_API_KEY_ID=$VID
            export VERACODE_API_KEY_SECRET=$VKEY
            ./veracode scan --type repo --source $REPO_URL --format table --output results.json

        # Publishing artifacts
        - name: Step 3 - Use the Upload Artifact GitHub Action
          uses: actions/upload-artifact@v3
          with: 
            name: VeracodeContainerSecurityResults
            path: ./results.json
