name: VeracodeContainerSecurity

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

        - name: Branch name
          run: |
            echo 'Branch Name: '${{ github.ref_name }}
