name: VeracodeContainerSecurity

on:
  workflow_call:

jobs:
  ContainerScan:
    runs-on: ubuntu-latest
    steps:

        # Runs Veracode Container Security - Failing on failed Bult-In Policy
        - name: VERACODE CONTAINER SECURITY
          if: ${{ success() }}
          env:
            VID: ${{ SECRETS.VID }}
            VKEY: ${{ SECRETS.VKEY }}
            REPO_URL: ${{ GITHUB.server_url }}/${{ GITHUB.REPOSITORY }}
          run: |
            echo $REPO_URL
